<?php

namespace Spectasonic\Front\ContactBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * EnquiryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnquiryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllContacts() {

        return $this->createQueryBuilder('u')->getQuery()->getResult();
    }
    public function getOneContact($id) {
        $qb = $this
            ->createQueryBuilder('u')
            /*->leftJoin('u.enquiry', 'enq')*/
            /*->addSelect('enq')*/
            ->where('u.id = :id')
            ->setParameter('id', $id);
           /* ->orderBy('enq.type', 'ASC');*/

        return $qb
            ->getQuery()
            ->getSingleResult();


    }
}
