<?php

namespace Spectasonic\Back\ShopManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShopCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopCategoryRepository extends EntityRepository
{
}
