<?php

namespace Spectasonic\Back\ShopManagerBundle\Repository;

/**
 * User_contractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_contractRepository extends \Doctrine\ORM\EntityRepository
{
}
