<?php

namespace Spectasonic\Back\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HomepageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomepageRepository extends EntityRepository {

    public function getConfigurationHomepage() {
        $qb = $this->createQueryBuilder('h');
        
        return $qb->getQuery()->getResult();       
    }
    
    public function getFrontConfigurationHomepage($id) {
        
        //ch = table configurator_homepage
        $qb = $this->createQueryBuilder('ch');
        
        $qb
                ->leftJoin('ch.slider', 'csh')
                ->addSelect('csh')
                
                ->leftJoin('csh.slider', 's')
                ->addSelect('s')
                
                ->leftJoin('s.medias', 'm')
                ->addSelect('m')
                
                ->where('ch.id = :id')
                ->setParameter('id', $id)
                
                ->orderBy('m.id', 'ASC');
                
        
        return $qb->getQuery()->getSingleResult();    
        
        
        /*
         *  $qb = $this->createQueryBuilder('p');

        $qb
                ->join('p.mainimage', 'm')
                ->addSelect('m')
                ->join('p.category', 'c')
                ->addSelect('c')
                ->where('p.slug = :slug')
                ->setParameter('slug', $slug);

        return $qb->getQuery()->getSingleResult();
         */
        
    }

}
