<?php

namespace Spectasonic\Back\CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends EntityRepository {

    public function getAll() {
        $qb = $this->createQueryBuilder('S');
        $qb
                ->leftJoin('S.slider', 's')
                ->addSelect('s');

        return $qb->getQuery();
    }
    
    

}
