imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    auth_mode: "login"
    host:      "%mailer_host%"
    port:      "587"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Assetic Minimal Configuration to enable Assetic support
# http://symfony.com/doc/2.8/assetic/asset_management.html
assetic:
    bundles: [SpectasonicBackBlogBundle, SpectasonicBackGestionContactBundle, SpectasonicFrontContactBundle, SpectasonicFrontNewsBundle, SpectasonicBackCoreBundle, SpectasonicFrontCoreBundle, FOSUserBundle]
    debug: '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        
# FosUserBundle
fos_user:
    db_driver:                 orm
    firewall_name:             main
    user_class:                Spectasonic\Front\UserBundle\Entity\User
    service:                 
        mailer:                fos_user.mailer.twig_swift
    registration:
        form:
            type:              spectasonic_front_fos_user_register
            validation_groups: [Register, Default, Registration]
        confirmation:
            enabled:           true
            template:          email/registration/email.txt.twig
            from_email:
                address:       spectasonic@mambot.fr
                sender_name:   Spectasonic Registration
    profile:
        form:
            type:              spectasonic_front_fos_user_profile
    resetting:
        email:
            template:          SpectasonicFrontUserBundle:Resetting:email.txt.twig
            from_email:
                address:       spectasonic@mambot.fr
                sender_name:   Spectasonic Resetting
    group:
        group_class:           Spectasonic\Front\UserBundle\Entity\Group
    from_email:
        address:               spectasonic@mambot.fr
        sender_name:           Spectasonic
            
           
# Stof\DoctrineExtensionsBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true        
            
   
fm_elfinder:
    assets_path: /assets
    instances:
        form_video:
            locale: %locale%
            editor: form
            fullscreen: true
            include_assets: true
            connector:
                debug: false
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/video
                        upload_allow: ['video/mp4']
                        upload_deny: ['all']
                        upload_max_size: 200M
        form_document:
            locale: %locale%
            editor: form
            fullscreen: true
            include_assets: true
            connector:
                debug: false
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/documents
                        upload_allow: ['text/csv', 'video/mp4', 'application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 8M
        
        form_image:
            locale: %locale%
            editor: form #
            fullscreen: true
            include_assets: true
            connector:
                debug: false
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/images
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'image/gif']
                        upload_deny: ['all']
                        upload_max_size: 8M
        
        ckeditor:
            locale:                     %locale%
            editor:                     ckeditor
            include_assets:             true
            connector:
                debug:                  false
                roots:       
                    uploads:
                        driver:          LocalFileSystem
                        path:            uploads
                        upload_allow:    ['image/png', 'image/jpg', 'image/jpeg', 'image/gif', 'audio/mpeg', 'text/csv', 'video/mp4', 'application/pdf']
                        upload_deny:     ['all']
                        upload_max_size: 8M
                        
                        
ivory_ck_editor:
    plugins:
        image2:
            path: "/ckeditor/plugins/image2/"
            filename: "plugin.js"
        btgrid:
            path: "/ckeditor/plugins/btgrid/"
            filename: "plugin.js"
        lineutils:
            path: "/ckeditor/plugins/lineutils/"
            filename: "plugin.js"
        widget:
            path: "/ckeditor/plugins/widget/"
            filename: "plugin.js"
        wordcount:
            path: "/ckeditor/plugins/wordcount/"
            filename: "plugin.js"
        undo:
            path: "/ckeditor/plugins/undo/"
            filename: "plugin.js"
        notification:
            path: "/ckeditor/plugins/notification/"
            filename: "plugin.js"
        htmlwriter:
            path: "/ckeditor/plugins/htmlwriter/"
            filename: "plugin.js"
        notificationaggregator:
            path: "/ckeditor/plugins/notificationaggregator/"
            filename: "plugin.js"
    default_config: my_config
    configs:
        my_config:
            toolbar: "my_toolbar_1"
            extraPlugins: "image2,btgrid,widget,lineutils,wordcount,undo,notification,htmlwriter,notificationaggregator"
            language: %locale%
            height:   '600px'     
            uiColor:  '#ffffff'
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters:
                instance: ckeditor
            wordcount:
                    showCharCount:       true
                    countSpacesAsChars:  false
                    maxCharCount:        3000
                    maxWordCount:        1000
                    countHTML:           false
            undo:
                undoStackSize: 200
    toolbars:
        configs:
            my_toolbar_1: [ [ 'Preview' ], [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ], [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ], [ 'Source' ], [ "About" ], "/", [ 'Bold','Italic','Underline','Strike', 'Blockquote','Subscript','Superscript','-','RemoveFormat' ], [ 'NumberedList','BulletedList','-','Outdent','Indent','-','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ], [ 'Link','Unlink','Anchor' ], [ 'pbckcode', 'Image', 'Video', 'Table','SpecialChar','Iframe', 'btgrid' ], '/', [ 'Styles', 'Format','Font','FontSize' ], [ 'TextColor','BGColor' ], [ 'RemoveFormat' ], [ 'Maximize' ] ]
        
            
            
                    
    