# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        #Spectasonic\Front\UserBundle\Entity\User: plaintext
        Spectasonic\Front\UserBundle\Entity\User: sha512
        # ou bien  FOS\UserBundle\Model\UserInterface: sha512 ???
    
    role_hierarchy:
        ROLE_USER:        [ROLE_USER]
        ROLE_VENDEUR:     [ROLE_VENDEUR]
        ROLE_MODERATEUR:  [ROLE_MODERATEUR]
        ROLE_EDITEUR:     [ROLE_EDITEUR]
        ROLE_ADMIN:       [ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
                    
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # Back area for admin only
        back:
            context:                 primary_auth
            pattern:                 ^/back  
            form_login:      
                provider:            fos_userbundle
                login_path:          spectasonic_back_core_security_login
                use_forward:         true
                use_referer:         true
                check_path:          spectasonic_back_core_security_check
                default_target_path: spectasonic_back_core_homepage
            logout:
                path:                spectasonic_back_core_security_logout
                target:              spectasonic_back_core_security_login
            anonymous:               true
        
        # default area for standard users
        main:
            context:                 primary_auth
            pattern:                 ^/
            anonymous:               true
            form_login:
                provider:            fos_userbundle
                login_path:          fos_user_security_login
                check_path:          fos_user_security_check
                use_forward:         true
                use_referer:         true
                default_target_path: fos_user_profile_show
            logout:
                path:                fos_user_security_logout
                target:              spectasonic_front_core_homepage
            remember_me:
                key:                 %secret%
    
    access_control:
        # back-office
        - { path: ^/back/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/back/logout$, role: [ROLE_ADMIN, ROLE_EDITEUR, ROLE_VENDEUR, ROLE_MODERATEUR] }
        - { path: ^/back, roles:[ROLE_ADMIN, ROLE_EDITEUR, ROLE_VENDEUR, ROLE_MODERATEUR]  }
        - { path: ^/account, roles: ROLE_USER }
        # front-office
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mot-de-passe-oublie, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/efconnect, role: [ROLE_ADMIN, ROLE_EDITEUR, ROLE_VENDEUR, ROLE_MODERATEUR] }
        - { path: ^/elfinder, role: [ROLE_ADMIN, ROLE_EDITEUR, ROLE_VENDEUR, ROLE_MODERATEUR] }
        