parameters:
    mon_parametre: 50

services:
#    spectasonic_platform.example:
#        class: Spectasonic\Front\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    spectasonic_back_blog.antispam:
        class: Spectasonic\Back\BlogBundle\Antispam\SpectasonicAntispam
        arguments: [@mailer, %locale%, 50] #Tableau d'arguments
