<?php

namespace Spectasonic\Front\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
#use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    
    public function getAllUsers() {
       /* $queryBuilder = $this->createQueryBuilder('u');
          $query = $queryBuilder->getQuery();
          $results = $query->getResult();
          return $results;
        */
        
        return $this->createQueryBuilder('u')->getQuery()->getResult();
        
        
    }
    
    public function getOneUser($id) {
       $qb = $this
               ->createQueryBuilder('u')
               ->leftJoin('u.address', 'addr')
               ->addSelect('addr')
               ->where('u.id = :id')
               ->setParameter('id', $id)
               ->orderBy('addr.type', 'ASC');
       
       return $qb
               ->getQuery()
               ->getSingleResult();
        
        
    }
}
