<?php

namespace Spectasonic\Back\BlogBundle\Repository;

/**
 * MediasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediasRepository extends \Doctrine\ORM\EntityRepository
{
}
