<?php

namespace Spectasonic\Back\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends EntityRepository {

    public function getSlider($id) {
        $qb = $this->createQueryBuilder('s');

        $qb
                ->join('s.medias', 'm')
                ->addSelect('m')
                ->orderBy('m.id', 'ASC')
                ->where('s.id = :id')
                ->setParameter('id', $id);

        return $qb->getQuery()->getSingleResult();
       
    }

}
