<?php

namespace Spectasonic\Back\UserManagerBundle\Repository;

/**
 * ContinentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContinentRepository extends \Doctrine\ORM\EntityRepository
{
}
