shop_contract:
    pattern:  /
    defaults: { _controller: "SpectasonicBackShopManagerBundle:Contract:index" }

shop_contract_show:
    pattern:  /{id}/show
    defaults: { _controller: "SpectasonicBackShopManagerBundle:Contract:show" }

shop_contract_new:
    pattern:  /new
    defaults: { _controller: "SpectasonicBackShopManagerBundle:Contract:new" }

shop_contract_create:
    pattern:  /create
    defaults: { _controller: "SpectasonicBackShopManagerBundle:Contract:create" }
    requirements: { _method: post }

shop_contract_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SpectasonicBackShopManagerBundle:Contract:edit" }

shop_contract_update:
    pattern:  /{id}/update
    defaults: { _controller: "SpectasonicBackShopManagerBundle:Contract:update" }
    requirements: { _method: post|put }

shop_contract_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SpectasonicBackShopManagerBundle:Contract:delete" }
    requirements: { _method: post|delete }

